### PR TITLE
Add Website folder in H5assembler repo

### PR DESCRIPTION
**Pull request by bricekk**
Add .website folder which will content the website based on the documentation of H5assembler - Using [`VitePress`](vitepress.vuejs.org`)
By the way, the webiste will look like their own
# Pull Request

## Description:

I added the .website folder, this folder will content the website of this project. The website will be based on the documentation. I did not use the [`H5A.github.io`](https://github.com/bricekk/H5A.github.io) repository just to follow the common structure.
I will not have a problem to move it to the [`H5A.github.io`](https://github.com/bricekk/H5A.github.io) repo.

Issue : #6 

#### In the `.website` folder run:
`yarn install`
#### Then to start the server listening (in hot reload) to http://localhost:5173/, run:
`yarn docs:dev`

### CODE REVIEW

**Comment by bricekk** [comment]
I'll continue on Sunday 🙏🏽

**Comment by ngdream** [comment]
hi bro  i really love your design:

please make your pull request in this repository please : https://github.com/ngdream/H5A.github.io

**Comment by ngdream** [comment]
thanks 😄

**Comment by bricekk** [comment]
you're welcome, i'm glad 😄 
I made the PR to the other repo. this one can be closed

**Pull request closed without merging**
